name: Node.js CI

on:
  [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      env:
        DEPLOYER_PK: ${{ secrets.DEPLOYER_PK }}
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm install
    - run: npx hardhat test